/* 학과 */		SELECT * FROM TB_DEPARTMENT;   
/* 학생 */		SELECT * FROM TB_STUDENT;
/* 과목 */		SELECT * FROM TB_CLASS;
/* 과목 교수 */	SELECT * FROM TB_CLASS_PROFESSOR;
/* 교수 */		SELECT * FROM TB_PROFESSOR;
/* 성적 */		SELECT * FROM TB_GRADE;


--1. 춘 기술대학교 학과 이름과 계열 표시
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;


--2. 학과의 학과 정원

SELECT CONCAT( 
				CONCAT (DEPARTMENT_NAME,'의 정원은 ') ,
				CONCAT(CAPACITY,' 명 입니다.') ) AS "학과별 정원"
FROM TB_DEPARTMENT;



--3. "국어국문학과" 휴학중인 여학생

SELECT STUDENT_NAME
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING ( DEPARTMENT_NO )
WHERE ABSENCE_YN = 'Y'
AND DEPARTMENT_NO = 001
AND SUBSTR(STUDENT_SSN, 8, 1) = 2;


--4. 도서관에서 대출 장기연체자

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = 'A513119'
OR STUDENT_NO = 'A513110'
OR STUDENT_NO = 'A513091'
OR STUDENT_NO = 'A513090'
OR STUDENT_NO = 'A513079'
order BY STUDENT_NO desc;

-- 5. 입학정원이 20명이 상 30명 이하인 학과들의 학과 이름과 계열

SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;


--6. 총장의 이름

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS null;

-- 7. 학과가 지정되지 않은 학생 확인

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL
OR DEPARTMENT_NO < 0;

-- 8. 수강신청 선수과목 확인

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 춘대학 모든 계열

SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

-- 10. 02 학번 전주 거주자
SELECT STUDENT_No, STUDENT_NAME, STUDENT_SSN,STUDENT_ADDRESS,ENTRANCE_DATE
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS, 1, 3) = '전주시'
AND SUBSTR(TO_CHAR(ENTRANCE_DATE, 'YYYY'), 1, 4) = '2002'
AND ABSENCE_YN='N';

------------------------------------------------------------------------------------
/* 학과 */		SELECT * FROM TB_DEPARTMENT;   
/* 학생 */		SELECT * FROM TB_STUDENT;
/* 과목 */		SELECT * FROM TB_CLASS;
/* 과목 교수 */	SELECT * FROM TB_CLASS_PROFESSOR;
/* 교수 */		SELECT * FROM TB_PROFESSOR;
/* 성적 */		SELECT * FROM TB_GRADE;

-- 1. 영어영문학과 입학년도 빠른순

SELECT STUDENT_No 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING ( DEPARTMENT_NO )
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;


-- 2 . 이름이 세글자가 아닌 교수

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


-- 3. 남자 교수들의 이름과 나이 나이가 적은 순서 (만나이계산)

SELECT PROFESSOR_NAME 교수이름, 
TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')) 
- TO_NUMBER(SUBSTR(PROFESSOR_SSN,1,2))
-1900 AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY PROFESSOR_SSN desc;

-- 4. 교수 이름 2글자

SELECT SUBSTR(PROFESSOR_NAME, 2) 교수이름
FROM TB_PROFESSOR;

-- 5. 재수생 입학자 (19살이면 현역)

SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE TO_NUMBER(TO_CHAR(ENTRANCE_DATE,'YYYY'))
-TO_NUMBER(SUBSTR(STUDENT_SSN,1,2))-1901 >= 19;

--6. 2020년 크리마스 요일

SELECT TO_CHAR(TO_DATE('20201225','YYYYMMDD'),'DAY') 크리스마스
FROM dual;

--7. YY와 RR 구분, YY는 21세기 그대로 RR은 50이상이면 20세기
 SELECT 
TO_DATE('99/10/11','YY/MM/DD') AS "1번",
TO_DATE('49/10/11','YY/MM/DD') AS "2번",
TO_DATE('99/10/11','RR/MM/DD') AS "3번",
TO_DATE('49/10/11','RR/MM/DD') AS "4번"
 FROM dual;

-- 8. 2000년도 이전 학번 학생

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 9. 한아름 학점 평점

SELECT round(avg(point),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10. 학과별 학생수

SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11. 지도교수 없는 학생

SELECT COUNT(*) COACH_PROFESSOR_NO
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS null;

-- 12. 김고운 평점

SELECT SUBSTR(TERM_NO,1,4) "년도", round(avg(point),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

-- 13. 학과별 휴학생수

SELECT DEPARTMENT_NO "학과코드명",
sum(CASE WHEN ABSENCE_YN = 'Y' THEN 1 ELSE 0 end)"휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14. 동명이인

SELECT STUDENT_NAME "동일이름",
sum(CASE WHEN STUDENT_NAME = STUDENT_NAME THEN 1 ELSE 0 end)"동명인 수"
FROM TB_STUDENT
HAVING COUNT(*) > 1
GROUP BY STUDENT_NAME
ORDER BY STUDENT_NAME;

-- 15. 김고운 학점 part2

SELECT nvl(SUBSTR(TERM_NO,1,4),' ') "년도",nvl(SUBSTR(TERM_NO,5,2),' ') "학기", round(avg(point),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1,4);


----------------------------------------------------------------------------------------
/* 학과 */		SELECT * FROM TB_DEPARTMENT;   
/* 학생 */		SELECT * FROM TB_STUDENT;
/* 과목 */		SELECT * FROM TB_CLASS;
/* 과목 교수 */	SELECT * FROM TB_CLASS_PROFESSOR;
/* 교수 */		SELECT * FROM TB_PROFESSOR;
/* 성적 */		SELECT * FROM TB_GRADE;

-- 1. 학생 이름과 주소(오름차순)
SELECT STUDENT_NAME "학생이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- 2. 휴학생 나이 적은순
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3. 90년대 학번중 주소지가 강원도나 경기도

SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE 
(STUDENT_ADDRESS LIKE '%경기도%'
OR 
STUDENT_ADDRESS LIKE '%강원도%')
AND STUDENT_NO LIKE '9%'
ORDER BY STUDENT_NAME;

--4. 




















































