/* 학과 */		SELECT * FROM TB_DEPARTMENT;   
/* 학생 */		SELECT * FROM TB_STUDENT;
/* 과목 */		SELECT * FROM TB_CLASS;
/* 과목 교수 */	SELECT * FROM TB_CLASS_PROFESSOR;
/* 교수 */		SELECT * FROM TB_PROFESSOR;
/* 성적 */		SELECT * FROM TB_GRADE;


--1. 춘 기술대학교 학과 이름과 계열 표시
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;


--2. 학과의 학과 정원

SELECT CONCAT( 
				CONCAT (DEPARTMENT_NAME,'의 정원은 ') ,
				CONCAT(CAPACITY,' 명 입니다.') ) AS "학과별 정원"
FROM TB_DEPARTMENT;



--3. "국어국문학과" 휴학중인 여학생

SELECT STUDENT_NAME
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING ( DEPARTMENT_NO )
WHERE ABSENCE_YN = 'Y'
AND DEPARTMENT_NO = 001
AND SUBSTR(STUDENT_SSN, 8, 1) = 2;


--4. 도서관에서 대출 장기연체자

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = 'A513119'
OR STUDENT_NO = 'A513110'
OR STUDENT_NO = 'A513091'
OR STUDENT_NO = 'A513090'
OR STUDENT_NO = 'A513079'
order BY STUDENT_NO desc;

-- 5. 입학정원이 20명이 상 30명 이하인 학과들의 학과 이름과 계열

SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;


--6. 총장의 이름

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS null;

-- 7. 학과가 지정되지 않은 학생 확인

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL
OR DEPARTMENT_NO < 0;

-- 8. 수강신청 선수과목 확인

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 춘대학 모든 계열

SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

-- 10. 02 학번 전주 거주자
SELECT STUDENT_No, STUDENT_NAME, STUDENT_SSN,STUDENT_ADDRESS,ENTRANCE_DATE
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS, 1, 3) = '전주시'
AND SUBSTR(TO_CHAR(ENTRANCE_DATE, 'YYYY'), 1, 4) = '2002'
AND ABSENCE_YN='N';

------------------------------------------------------------------------------------
/* 학과 */		SELECT * FROM TB_DEPARTMENT;   
/* 학생 */		SELECT * FROM TB_STUDENT;
/* 과목 */		SELECT * FROM TB_CLASS;
/* 과목 교수 */	SELECT * FROM TB_CLASS_PROFESSOR;
/* 교수 */		SELECT * FROM TB_PROFESSOR;
/* 성적 */		SELECT * FROM TB_GRADE;

-- 1. 영어영문학과 입학년도 빠른순

SELECT STUDENT_No 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING ( DEPARTMENT_NO )
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;


-- 2 . 이름이 세글자가 아닌 교수

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


-- 3. 남자 교수들의 이름과 나이 나이가 적은 순서 (만나이계산)

SELECT PROFESSOR_NAME 교수이름, 
TO_CHAR(TO_DATE( SUBSTR( PROFESSOR_SSN, 1, INSTR(PROFESSOR_SSN, '-') - 1), 'RRMMDD' ),'YYYY') - 2024


"나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY PROFESSOR_SSN desc;



SELECT PROFESSOR_NAME 교수이름, PROFESSOR_SSN "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY PROFESSOR_SSN desc;

